import Vue from 'vue'
import {
  Button,
  Container,
  Header,
  Main,
  Footer,
  Card,
  Collapse,
  CollapseItem,
  Table,
  TableColumn,
  Row,
  Col,
  Menu,
  Submenu,
  MenuItem,
  Form,
  FormItem,
  Input,
  Avatar,
  Dialog,
  Link,
  Drawer,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Switch,
  Checkbox,
  CheckboxGroup,
  Select,
  Option,
  Tabs,
  TabPane,
  Breadcrumb,
  BreadcrumbItem,
  Descriptions,
  DescriptionsItem,
  Pagination,
  Aside,
  Cascader,
  DatePicker,
  Upload,
  Radio,
  RadioGroup,
  RadioButton,
  Message,
  MessageBox
} from 'element-ui'

Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Card)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Row)
Vue.use(Col)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Avatar)
Vue.use(Dialog)
Vue.use(Link)
Vue.use(Drawer)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Switch)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Select)
Vue.use(Option)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Descriptions)
Vue.use(DescriptionsItem)
Vue.use(Pagination)
Vue.use(Aside)
Vue.use(Cascader)
Vue.use(DatePicker)
Vue.use(Upload)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(RadioButton)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
